# Generated by Django 3.1.2 on 2020-10-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20201021_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(auto_now=True),
        ),
    ]
